# Your Title Here

**Name(s)**: (your name(s) here)

**Website Link**: (your website link)

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
pd.options.plotting.backend = 'plotly'

from dsc80_utils import * # Feel free to uncomment and use this.

## Step 1: Introduction

In [5]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [11]:
outage = pd.read_excel('outage.xlsx',
                       header = 5, 
                       skiprows = [6],
                       usecols="B:BE")
outage
question = "Where and when do power outrages occurr?"

## Step 2: Data Cleaning and Exploratory Data Analysis

In [16]:
#added two columns outage.start and outage.restoration
outage['OUTAGE.START'] = (
    pd.to_datetime(outage['OUTAGE.START.DATE']) +
    pd.to_timedelta(outage['OUTAGE.START.TIME'].astype(str))
)

outage['OUTAGE.RESTORATION'] = (
    pd.to_datetime(outage['OUTAGE.RESTORATION.DATE']) +
    pd.to_timedelta(outage['OUTAGE.RESTORATION.TIME'].astype(str))
)
outage

,OBS,YEAR,MONTH,U.S._STATE,...,PCT_WATER_TOT,PCT_WATER_INLAND,OUTAGE.START,OUTAGE.RESTORATION
0,1,2011,7.0,Minnesota,...,8.41,5.48,2011-07-01 17:00:00,2011-07-03 20:00:00
1,2,2014,5.0,Minnesota,...,8.41,5.48,2014-05-11 18:38:00,2014-05-11 18:39:00
2,3,2010,10.0,Minnesota,...,8.41,5.48,2010-10-26 20:00:00,2010-10-28 22:00:00
...,...,...,...,...,...,...,...,...,...
1531,1532,2009,8.0,South Dakota,...,1.69,1.69,2009-08-29 22:54:00,2009-08-29 23:53:00
1532,1533,2009,8.0,South Dakota,...,1.69,1.69,2009-08-29 11:00:00,2009-08-29 14:01:00
1533,1534,2000,NaN,Alaska,...,14.24,2.90,NaT,NaT

In [24]:
outage['OUTAGE.RESTORATION'].dtypes
outage.columns

Index(['OBS', 'YEAR', 'MONTH', 'U.S._STATE', 'POSTAL.CODE', 'NERC.REGION',
       'CLIMATE.REGION', 'ANOMALY.LEVEL', 'CLIMATE.CATEGORY',
       'OUTAGE.START.DATE', 'OUTAGE.START.TIME', 'OUTAGE.RESTORATION.DATE',
       'OUTAGE.RESTORATION.TIME', 'CAUSE.CATEGORY', 'CAUSE.CATEGORY.DETAIL',
       'HURRICANE.NAMES', 'OUTAGE.DURATION', 'DEMAND.LOSS.MW',
       'CUSTOMERS.AFFECTED', 'RES.PRICE', 'COM.PRICE', 'IND.PRICE',
       'TOTAL.PRICE', 'RES.SALES', 'COM.SALES', 'IND.SALES', 'TOTAL.SALES',
       'RES.PERCEN', 'COM.PERCEN', 'IND.PERCEN', 'RES.CUSTOMERS',
       'COM.CUSTOMERS', 'IND.CUSTOMERS', 'TOTAL.CUSTOMERS', 'RES.CUST.PCT',
       'COM.CUST.PCT', 'IND.CUST.PCT', 'PC.REALGSP.STATE', 'PC.REALGSP.USA',
       'PC.REALGSP.REL', 'PC.REALGSP.CHANGE', 'UTIL.REALGSP', 'TOTAL.REALGSP',
       'UTIL.CONTRI', 'PI.UTIL.OFUSA', 'POPULATION', 'POPPCT_URBAN',
       'POPPCT_UC', 'POPDEN_URBAN', 'POPDEN_UC', 'POPDEN_RURAL',
       'AREAPCT_URBAN', 'AREAPCT_UC', 'PCT_LAND', 'PCT_WATER_TOT',
       'PCT_WATER_INLAND', 'OUTAGE.START', 'OUTAGE.RESTORATION'],
      dtype='object')

In [25]:
shouldn_be_blank = outage[['OBS', 'YEAR', 'MONTH', 'U.S._STATE', 'POSTAL.CODE', 'NERC.REGION',
                             'CLIMATE.REGION', 'ANOMALY.LEVEL', 'CLIMATE.CATEGORY',
       'OUTAGE.START.DATE', 'OUTAGE.START.TIME', 'OUTAGE.RESTORATION.DATE',
       'OUTAGE.RESTORATION.TIME', 'CAUSE.CATEGORY', 'OUTAGE.DURATION',  'CUSTOMERS.AFFECTED']]

In [27]:
outage['DURATION_HOURS'] = (outage['OUTAGE.RESTORATION'] - outage['OUTAGE.START']).dt.total_seconds() / 3600
outage

,OBS,YEAR,MONTH,U.S._STATE,...,PCT_WATER_INLAND,OUTAGE.START,OUTAGE.RESTORATION,DURATION_HOURS
0,1,2011,7.0,Minnesota,...,5.48,2011-07-01 17:00:00,2011-07-03 20:00:00,51.00
1,2,2014,5.0,Minnesota,...,5.48,2014-05-11 18:38:00,2014-05-11 18:39:00,0.02
2,3,2010,10.0,Minnesota,...,5.48,2010-10-26 20:00:00,2010-10-28 22:00:00,50.00
...,...,...,...,...,...,...,...,...,...
1531,1532,2009,8.0,South Dakota,...,1.69,2009-08-29 22:54:00,2009-08-29 23:53:00,0.98
1532,1533,2009,8.0,South Dakota,...,1.69,2009-08-29 11:00:00,2009-08-29 14:01:00,3.02
1533,1534,2000,NaN,Alaska,...,2.90,NaT,NaT,NaN

In [ ]:
outage['DURATION_HOURS'].max()

1811.8833333333334

In [33]:
fig = px.histogram(
    outage,
    x='DURATION_HOURS',
    nbins=20,  # exactly 20 bars
    title='Histogram of Power Outage Durations',
    labels={'DURATION_HOURS': 'Duration (hours)'},
    opacity=0.75
)

fig.update_layout(
    xaxis=dict(range=[0, outage['DURATION_HOURS'].max()]),
    yaxis_title='Count of Outages'
)

fig.show()

## Step 3: Assessment of Missingness

In [ ]:
# TODO

## Step 4: Hypothesis Testing

In [ ]:
# TODO

## Step 5: Framing a Prediction Problem

In [ ]:
# TODO

## Step 6: Baseline Model

In [ ]:
# TODO

## Step 7: Final Model

In [ ]:
# TODO

## Step 8: Fairness Analysis

In [ ]:
# TODO